### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by shahinsh** [gskielian/JPG-PNG-to-MNIST-NN-Format#1]
I followed your readme and after running the Python code I get following error.

`Traceback (most recent call last):`
 `File "convert-images-to-mnist-format.py", line 71, in <module>`
 `print average(pix[x,y])`
 `File "convert-images-to-mnist-format.py", line 9, in average`
   `return (pixel[0] + pixel[1] + pixel[2])/3`
` TypeError: 'int' object has no attribute '**getitem** '

Would you please give me a hint to solve this error ?

And in your readme you said 

 Change the appropriate labels in batches.meta.txt

what do you mean by that ?

**Comment by shahinsh** [comment]
The problem was that My input Image was already grayscale and I had to put a color Image .
